# Generated by Django 5.1.6 on 2025-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_weatherstation_author_weatherstation_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationunit',
            name='station_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
