# Generated by Django 5.1.6 on 2025-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_stationunit_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationunit',
            name='station_key',
            field=models.IntegerField(default=0),
        ),
    ]
